#!/usr/bin/env bash
# This script display information about subdomains

print_subdomain_info () {
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4 " " $5}')
	echo "$line" "$2" | awk '{print "The subdomain " $3 " is a " $1 " record and points to " $2}'
}

if [ "$#" == 2 ]
then
  print_subdomain_info "$1" "$2"
else
  print_subdomain_info "$1" "www"
  print_subdomain_info "$1" "lb-01"
  print_subdomain_info "$1" "web-01"
  print_subdomain_info "$1" "web-02"
fi
