#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.nginx-debian.html index.htm;
}
" > /etc/nginx/sites_available/default

service nginx restart
