#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.nginix-debian.html index.htm;
     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
     }
}
" > /etc/nginx/sites-available/default

service nginx restart
