#!/usr/bin/env bash
# this script fix this container so that Nginx is running as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo --user nginx service nginx start
